// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using Web03.Data;

namespace Web03.Migrations
{
    [DbContext(typeof(RoomDb))]
    partial class RoomDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Web03.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Attendees");

                    b.Property<string>("By");

                    b.Property<DateTime>("From");

                    b.Property<string>("Name");

                    b.Property<int?>("RoomId");

                    b.Property<DateTime>("To");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Web03.Models.Room", b =>
                {
                    b.Property<int>("Id");

                    b.Property<int>("MaxSeat");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Web03.Models.Booking", b =>
                {
                    b.HasOne("Web03.Models.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId");
                });
#pragma warning restore 612, 618
        }
    }
}
